config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

 resources :restaurants

  # # Lire tous les restaurants
  # get 'restaurants', to: 'restaurants#index'

  # # Lire un restaurant
  # get 'restaurants/:id', to: 'restaurants#show', as: :restaurant

  # # Create a restaurant (2 requests)
  # # The `new` route needs to be *before* `show` route.
  # get 'restaurants/new', to: 'restaurants#new' # affiche le formulaire
  # post 'restaurants', to: 'restaurants#create' # enregistre le formulaire en db

  # # Update a restaurant (2 requests)
  # # Affiche form prerempli pr editer l'enregistrement
  # get 'restaurants/:id/edit', to: 'restaurants#edit'
  # # Recupere les donnees saisies pour les modifier en db
  # patch 'restaurants/:id', to: 'restaurants#update'

  # # supprimer un restaurant
  # delete 'restaurants/:id', to: 'restaurants#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: [:show, :edit, :update, :destroy]

  def index
    @restaurants = Restaurant.all
  end

  def show
    # @restaurant = Restaurant.find(params[:id])
  end

  def new
    @restaurant = Restaurant.new # needed to instantiate the form_for
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    @restaurant.save
    redirect_to restaurants_path
  end

  def edit
    @restaurant = Restaurant.find(params[:id])
  end

  def update
    # @restaurant = Restaurant.find(params[:id])
    @restaurant.update(restaurant_params)
    redirect_to restaurant_path(@restaurant)
  end

  def destroy
    # @restaurant = Restaurant.find(params[:id])
    @restaurant.destroy
    redirect_to restaurants_path
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :rating)
  end

  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ThespoonWithActiverecord</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/_form.html.erb
<%= simple_form_for(restaurant) do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :rating %>
  <%= f.submit %>
<% end %>

app/views/restaurants/edit.html.erb
<%= render "form", restaurant: @restaurant %>

<%= link_to "Back to list", restaurants_path %> |

<%= link_to "Back to restaurant", restaurant_path %>

app/views/restaurants/index.html.erb
<h1>Les restaurants</h1>

<% @restaurants.each do |restaurant| %>
<h2><%= restaurant.name %></h2>
<p><%= restaurant.address %></p>
<p>* <%= restaurant.rating %></p>
<%= link_to "Allez voir", restaurant_path(restaurant) %> |
<%= link_to "Edit", edit_restaurant_path(restaurant) %> |
<%= link_to "Delete",restaurant_path(restaurant),
method: :delete,
data: { confirm: "Are you sure?" } %>

<p>---</p>
<% end %>

app/views/restaurants/new.html.erb
<%= render "form", restaurant: @restaurant %>

app/views/restaurants/show.html.erb
<h1><%= @restaurant.name %></h1>
<p><%= @restaurant.address %></p>
<p><%= @restaurant.rating %></p>

<%= link_to "Back to list", restaurants_path %> |

<%= link_to "Edit '#{@restaurant.name}'",
edit_restaurant_path(@restaurant) %> |

<%= link_to "Delete '#{@restaurant.name}'",
restaurant_path(@restaurant),
method: :delete,
data: { confirm: "Are you sure?" } %>